ALTER TYPE "ImportBatchStatus" ADD VALUE IF NOT EXISTS 'ROWS_APPLIED';
ALTER TYPE "ImportBatchStatus" ADD VALUE IF NOT EXISTS 'MATERIALIZED';
ALTER TYPE "ImportBatchStatus" ADD VALUE IF NOT EXISTS 'MATERIALIZATION_FAILED';
