import type { Page } from "@playwright/test";

/** Inspect the exported bytes independently of native browser download-folder locks. */
export async function observePngExport(page: Page) {
  await page.evaluate(() => {
    const original = URL.createObjectURL;
    URL.createObjectURL = blob => {
      if (blob instanceof Blob && blob.type === "image/png") (window as Window & { exportedPng?: Promise<string> }).exportedPng = new Promise((resolve, reject) => {
        const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(blob);
      });
      return original(blob);
    };
  });
  return async () => {
    const data = await page.evaluate(() => (window as Window & { exportedPng?: Promise<string> }).exportedPng);
    if (!data?.startsWith("data:image/png;base64,")) throw new Error("No PNG was generated by the export action.");
    return Buffer.from(data.split(",")[1], "base64");
  };
}
