import { expect, test } from "@playwright/test";
import { prisma } from "../../src/lib/prisma";
import { defaultPreferences } from "../../src/lib/workstation/types";
import { candleFixture } from "./candle-fixture";

test.afterAll(() => prisma.$disconnect());

test("session changes isolate requests, cancel stale history, and persist through the saved-view API", async ({ page, context }) => {
  const trade = await prisma.closedTrade.findFirstOrThrow({ where: { account: { ibkrAccount: "DEMO-WORKSTATION" }, isStale: false }, orderBy: { closeTime: "desc" } });
  const csrf = await (await context.request.get("/api/auth/csrf")).json();
  await context.request.post("/api/auth/callback/credentials", { form: { csrfToken: csrf.csrfToken, username: "phase2-reviewer", password: "phase2-local-test-only", json: "true" } });
  const endpoint = `/api/closed-trades/${encodeURIComponent(trade.groupKey)}/workstation/view`;
  const saved = await (await context.request.get(endpoint)).json();
  const panels = defaultPreferences().panels.map(panel => ({ ...panel, session: "regular", benchmark: panel.id === "chart-1" ? "SPY" : "off", range: { from: Math.floor(trade.openTime.getTime() / 1000) - 3 * 86400, to: Math.floor(trade.closeTime.getTime() / 1000) + 86400 } }));
  expect((await context.request.patch(endpoint, { data: { expectedRevision: saved.revision, view: { version: 1, arrangement: "left", panels } } })).ok()).toBe(true);
  const requests: { interval: string; session: string; purpose: string | null }[] = [], errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  let release: (() => void) | undefined;
  let delayExtended = false;
  await page.route("**/api/workstation/candles?**", async route => {
    const url = new URL(route.request().url()), p = url.searchParams;
    const interval = p.get("timeframe")!, session = p.get("session")!;
    if (p.get("mode") !== "cache") requests.push({ interval, session, purpose: p.get("purpose") });
    if (delayExtended && session === "extended" && !p.has("purpose") && p.get("mode") !== "cache") await new Promise<void>(resolve => { release = resolve; });
    await route.fulfill({ json: candleFixture(route.request().url()) }).catch(() => {});
  });
  await page.goto(`/trades?account=DEMO-WORKSTATION&groupKey=${encodeURIComponent(trade.groupKey)}`);
  await expect(page.locator(".ws-chart")).toHaveCount(3);
  for (const chart of await page.locator(".ws-chart").all()) await expect(chart).toHaveAttribute("data-visible-from", /\d+/);
  await expect(page.locator(".ws-chart-state,.ws-history-progress")).toHaveCount(0);
  const first = page.locator('[data-chart-id="chart-1"]');
  const range = [Number(await first.getAttribute("data-visible-from")), Number(await first.getAttribute("data-visible-to"))];
  requests.length = 0;
  delayExtended = true;
  await first.getByLabel("Chart session chart-1", { exact: true }).selectOption("extended");
  await expect.poll(() => !!release).toBe(true);
  await first.getByLabel("Chart session chart-1", { exact: true }).selectOption("regular");
  release!(); delayExtended = false;
  await expect(first).toHaveAttribute("data-session", "regular");
  await expect(page.locator(".ws-chart-state,.ws-history-progress")).toHaveCount(0);
  await expect(first.locator('[data-ohlc="close"]')).toHaveText("101.00");
  expect(requests.filter(request => request.interval !== "5m")).toEqual([]);
  await first.getByLabel("Chart session chart-1", { exact: true }).selectOption("extended");
  await expect(page.locator(".ws-chart-state,.ws-history-progress")).toHaveCount(0);
  await expect(first.locator('[data-ohlc="close"]')).toHaveText("111.00");
  await expect.poll(async () => (await (await context.request.get(endpoint)).json()).view.panels.map((panel: { session: string }) => panel.session)).toEqual(["extended", "regular", "regular"]);
  expect(Math.abs(Number(await first.getAttribute("data-visible-from")) - range[0])).toBeLessThanOrEqual(300);
  expect(Math.abs(Number(await first.getAttribute("data-visible-to")) - range[1])).toBeLessThanOrEqual(300);
  expect(requests.some(request => request.purpose === "benchmark" && request.session === "extended")).toBe(true);
  requests.length = 0;
  await page.getByRole("button", { name: "Chart settings", exact: true }).click();
  const settings = page.getByRole("dialog", { name: "Chart settings", exact: true });
  await settings.getByLabel("Volume average period (bars)", { exact: true }).fill("50");
  await settings.getByLabel("Horizontal gridlines", { exact: true }).uncheck();
  await settings.getByRole("button", { name: "Close dialog" }).click();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("execution-lab:workstation:preferences:application:v1")!).volumeAverage.period)).toBe(50);
  expect(requests).toEqual([]);
  await page.evaluate(() => localStorage.removeItem("execution-lab:workstation:preferences:application:v1"));
  await page.reload();
  await expect(first.getByLabel("Chart session chart-1", { exact: true })).toHaveValue("extended");
  await expect(page.getByLabel("Chart session chart-2", { exact: true })).toHaveValue("regular");
  expect(errors).toEqual([]);
});
