import { expect, test } from "@playwright/test";
import { prisma } from "../../src/lib/prisma";
import { defaultPreferences } from "../../src/lib/workstation/types";
import { fallbackLayout } from "../../src/lib/workstation/template-layout";
import { candleFixture } from "./candle-fixture";

test.afterAll(() => prisma.$disconnect());
test("authenticated template changes preserve legacy fields, evidence, autosave and reload", async ({ page, context }) => {
  const groupKey = "DEMO-NOTION-VALIDATION";
  const { csrfToken } = await (await context.request.get("/api/auth/csrf")).json();
  await context.request.post("/api/auth/callback/credentials", { form: { csrfToken, username: "phase2-reviewer", password: "phase2-local-test-only", json: "true" } });
  expect((await (await context.request.get("/api/auth/session")).json()).user.name).toBe("phase2-reviewer");
  const endpoint = `/api/closed-trades/${groupKey}/workstation`;
  let layout = structuredClone(fallbackLayout);
  layout.id = "browser-v1";
  const sourceId = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", key = `notion:${sourceId}` as const;
  layout.sections.push({ key, sourceId, path: [99], label: "Validation notes", groups: [], type: "heading_2" });
  await context.route("**/api/workstation/notion/template", route => route.fulfill({ json: { layout } }));
  await context.route("**/api/workstation/candles?**", route => route.fulfill({ json: candleFixture(route.request().url()) }));
  await page.addInitScript(prefs => localStorage.setItem("execution-lab:workstation:preferences:application:v1", JSON.stringify({ ...prefs, journal: true, panels: [{ id: "chart-1", interval: "5m" }] })), defaultPreferences());
  await page.goto(`/trades?account=DEMO-WORKSTATION&groupKey=${groupKey}`);
  await expect(page.locator("summary").filter({ hasText: /^Previous review fields$/i })).toHaveCount(0);
  await page.getByRole("button", { name: "Review details", exact: false }).click();
  const details = page.getByRole("dialog", { name: "Review details", exact: true });
  await expect(details.getByLabel("Mistake / improvement", { exact: true })).toHaveValue("Synthetic legacy improvement to preserve");
  await details.getByLabel("Mistake / improvement", { exact: true }).fill("Edited preserved improvement");
  await details.getByRole("button", { name: "Close Review details", exact: true }).click();
  await expect.poll(async () => (await (await context.request.get(endpoint)).json()).review.mistake).toBe("Edited preserved improvement");
  await page.locator("summary").filter({ hasText: /^Validation notes$/ }).click();
  const field = page.getByRole("textbox", { name: "Validation notes", exact: true });
  await field.fill("Saved dynamic note");
  await page.getByRole("button", { name: "Refresh Notion sections", exact: true }).focus();
  await expect.poll(async () => (await (await context.request.get(endpoint)).json()).review.notion.dynamicSections?.[key]?.html).toContain("Saved dynamic note");
  const section = page.locator("details.ws-template-section").filter({ has: page.locator("summary").filter({ hasText: /^Validation notes$/ }) });
  await section.getByRole("button", { name: "Attach image", exact: true }).click();
  const png = await page.evaluate(() => { const canvas = document.createElement("canvas"); canvas.width = 20; canvas.height = 20; return canvas.toDataURL().split(",")[1]; });
  const attach = page.getByRole("dialog", { name: "Attach image", exact: true });
  await attach.getByLabel("Choose image").setInputFiles({ name: "dynamic-evidence.png", mimeType: "image/png", buffer: Buffer.from(png, "base64") });
  await attach.getByRole("button", { name: "Attach image to Validation notes" }).click();
  await expect(attach).toHaveCount(0);
  await expect.poll(async () => (await (await context.request.get(endpoint)).json()).review.notion.dynamicSections?.[key]?.evidenceIds.length).toBe(1);
  layout = { ...layout, id: "browser-v2", sections: layout.sections.map(s => s.key === key ? { ...s, label: "Renamed validation notes" } : s) };
  await page.getByRole("button", { name: "Refresh Notion sections", exact: true }).click();
  await expect(page.locator("summary").filter({ hasText: /^Renamed validation notes$/ })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Renamed validation notes", exact: true })).toContainText("Saved dynamic note");
  layout = { ...layout, id: "browser-v3", archived: [...layout.archived, layout.sections.find(s => s.key === key)!], sections: layout.sections.filter(s => s.key !== key) };
  await page.getByRole("button", { name: "Refresh Notion sections", exact: true }).click();
  await expect(page.locator("summary").filter({ hasText: /^Renamed validation notes$/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Review details", exact: false }).click();
  await details.locator("summary").filter({ hasText: /^Renamed validation notes$/ }).click();
  await expect(details.getByRole("textbox", { name: "Renamed validation notes", exact: true })).toContainText("Saved dynamic note");
  await expect(details.getByRole("button", { name: /View dynamic-evidence/ })).toBeVisible();
  await page.keyboard.press("Escape"); await expect(details).toHaveCount(0);
  await page.reload(); await page.getByRole("button", { name: "Review details", exact: false }).click();
  await expect(details.getByLabel("Mistake / improvement", { exact: true })).toHaveValue("Edited preserved improvement");
  await expect.poll(async () => (await (await context.request.get(endpoint)).json()).review.notes).toContain("Synthetic legacy note to preserve");
});
