import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "../../src/lib/prisma";
import { listWorkstationTrades } from "../../src/lib/server/trade-workstation";
test("downloaded application backup includes reviews, drawings, images, interpretations and views", async ({ page, context }) => {
  const csrf = await (await context.request.get("/api/auth/csrf")).json();
  await context.request.post("/api/auth/callback/credentials", { form: { csrfToken: csrf.csrfToken, username: "phase2-reviewer", password: "phase2-local-test-only", json: "true", callbackUrl: "http://127.0.0.1:3101/trades" } });
  const trade = (await listWorkstationTrades({ account: "DEMO-WORKSTATION", symbol: "MU" }))[0];
  const url = `/api/closed-trades/${encodeURIComponent(trade.id)}/workstation`;
  const document = await (await context.request.get(url)).json();
  document.review.setup = "Retention verification — opening range reclaim";
  document.review.takeaway = "Review, chart and screenshot survive independent backup restoration.";
  document.drawings = [{ id: "retention-review-ray", tool: "ray", points: [{ time: trade.openTime, price: trade.entry }], text: "Opening entry", color: "#a5b4fc", width: 1.5, dashed: true, locked: false, hidden: false, panel: null, createdAt: trade.openTime }];
  const image = await fs.readFile("screenshots/cache-first-history/multichart-export.png");
  document.evidence = [{ id: "retention-review-chart", name: "Verified chart layout", image: `data:image/png;base64,${image.toString("base64")}`, timeframe: "5m / 1h / 1d", time: Date.now(), revision: document.revision, timeInterpretationVersion: trade.timeInterpretationVersion }];
  const saved = await context.request.patch(url, { data: { expectedRevision: document.revision, document } }); expect(saved.ok(), await saved.text()).toBe(true);
  await page.addInitScript(() => localStorage.setItem("execution-lab:backup-reminder:snoozed:v1", String(Date.now())));
  await page.goto(`/trades?account=DEMO-WORKSTATION&symbol=MU&groupKey=${encodeURIComponent(trade.id)}`);
  await expect(page.getByRole("region", { name: "MU 5m chart", exact: true })).toHaveAttribute("data-visible-bars", /[1-9]/);
  await page.waitForTimeout(1400);
  await fs.mkdir("screenshots/neon-personal-retention", { recursive: true });
  await page.screenshot({ path: "screenshots/neon-personal-retention/desktop-dark.png" });
  await page.getByTitle("Appearance", { exact: true }).click();
  await page.screenshot({ path: "screenshots/neon-personal-retention/desktop-light.png" });
  await page.setViewportSize({ width: 1366, height: 900 }); await page.screenshot({ path: "screenshots/neon-personal-retention/laptop-light.png" });
  await page.getByTitle("Appearance", { exact: true }).click(); await page.screenshot({ path: "screenshots/neon-personal-retention/laptop-dark.png" });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: "screenshots/neon-personal-retention/mobile-dark.png" });
  await page.getByRole("button", { name: "Open navigation", exact: true }).click(); await page.getByTitle("Appearance", { exact: true }).click(); await page.getByRole("button", { name: "Close navigation", exact: true }).click();
  await page.screenshot({ path: "screenshots/neon-personal-retention/mobile-light.png" });
  const backupResponse = await context.request.get("/api/admin/backup"); expect(backupResponse.ok(), await backupResponse.text()).toBe(true);
  const body = await backupResponse.text(), backup = JSON.parse(body);
  expect(Buffer.byteLength(body)).toBeLessThan(4_000_000);
  expect(backup.marketCandles).toEqual([]); expect(backup.workstationCandleChunks).toBeUndefined();
  expect(backup.workstationTradeViews.some((r: { groupKey: string }) => r.groupKey === trade.id)).toBe(true);
  expect(backup.closedTradeNotes.some((r: { workstationJson: string | null }) => r.workstationJson?.includes("retention-review-ray"))).toBe(true);
  expect(backup.assets.workstationEvidence.some((r: { id: string; bytes: number }) => r.id === "retention-review-chart" && r.bytes === image.length)).toBe(true);
  expect(backup.executionTimeInterpretations.length).toBeGreaterThan(0);
  const verified = await context.request.post("/api/admin/backup/verify", { data: body, headers: { "Content-Type": "application/json" } }); expect(verified.ok(), await verified.text()).toBe(true);
  const root = path.join(process.env.LOCALAPPDATA!, "TradeJournal", "release-backups");
  await fs.writeFile(path.join(root, "retention-representative-app.json"), body);
  console.log(JSON.stringify({ representativeBackupBytes: Buffer.byteLength(body), chartViews: backup.workstationTradeViews.length, screenshotBytes: image.length }));
  await prisma.$disconnect();
});
