import { notionReviewSchema } from "./notion-template";
import { richHtml } from "./rich-text";
import { z } from "zod";
import { drawingTools } from "./types";
import { IMAGE_MAX_BYTES, IMAGE_MAX_PIXELS } from "./image-assets";
const text = z.string().max(10000);
const point = z.object({ time: z.number().finite().nonnegative(), price: z.number().finite() });
const peerCapture = z.object({ arrangement: z.array(z.object({ symbol: z.string().max(40), x: z.number().finite(), y: z.number().finite(), width: z.number().positive(), height: z.number().positive() })).max(64).optional(), replayAt: z.number().finite().nonnegative().optional(), source: z.literal("peer-comparison"), symbols: z.array(z.string().max(40)).min(1).max(64), groupId: z.string().max(200), groupName: z.string().max(300), interval: z.enum(["5m", "10m", "15m", "1h", "1d", "1wk"]), session: z.enum(["regular", "extended"]), adjustment: z.enum(["raw", "split"]), ranges: z.record(z.string().max(40), z.object({ from: z.number().finite(), to: z.number().finite() })).refine(v => Object.keys(v).length <= 64), capturedAt: z.string().datetime(), beforeEntry: z.boolean(), entryTime: z.number().finite().nullable() }).strict();
export const drawingSchema = z.object({ id: z.string().min(1).max(200), tool: z.enum(drawingTools).exclude(["cursor"]), points: z.array(point).min(1).max(4), text: z.string().max(500), color: z.string().regex(/^#[a-fA-F0-9]{6}$/), width: z.number().min(.5).max(4), dashed: z.boolean(), showDefaultLabel: z.boolean().optional(), extendLeft: z.boolean().optional(), extendRight: z.boolean().optional(), showPrice: z.boolean().optional(), showValues: z.boolean().optional(), showPercent: z.boolean().optional(), showInterval: z.boolean().optional(), showBars: z.boolean().optional(), locked: z.boolean(), hidden: z.boolean(), panel: z.string().max(100).nullable(), createdAt: z.number().finite().nonnegative() }).superRefine((d, ctx) => { if (["trend", "arrow", "zone", "measure", "long", "short"].includes(d.tool) && d.points.length < 2) ctx.addIssue({ code: "custom", message: "This drawing needs two anchors" }); });
export const imageAssetSchema = z.object({ id: z.string().min(1).max(200), storage: z.enum(["r2", "demo"]), sha256: z.string().regex(/^[a-f0-9]{64}$/), bytes: z.number().int().positive().max(IMAGE_MAX_BYTES), width: z.number().int().positive(), height: z.number().int().positive(), mime: z.literal("image/png") }).strict().refine(a => a.width * a.height <= IMAGE_MAX_PIXELS, "Image exceeds 16 megapixels");
export const workstationDocumentSchema = z.object({
  evidenceProtocol: z.literal(2).optional(),
  comparison: z.object({ drawings: z.record(z.string().min(1).max(40), z.array(drawingSchema).max(500)).refine(v => Object.keys(v).length <= 200 && Object.values(v).reduce((sum, drawings) => sum + drawings.length, 0) <= 2000), arrangements: z.record(z.string().min(1).max(200), z.object({ order: z.array(z.string().max(40)).max(500), hidden: z.array(z.string().max(40)).max(500) })).refine(v => Object.keys(v).length <= 100) }).optional(),
  journalUpdatedAt: z.string().datetime().nullable().optional(),
  schema: z.literal(1), revision: z.number().int().min(0), updatedAt: z.string().datetime().nullable(), noteUpdatedAt: z.string().datetime().nullable().optional(), journalEntryId: z.string().nullable().optional(),
  review: z.object({ notion: notionReviewSchema.optional(), setup: text, execution: text, takeaway: text.transform(richHtml), notes: z.string().max(20000), thesis: text, exit: text, mistake: text, followUp: text, tags: z.array(z.string().trim().min(1).max(60)).max(30), status: z.enum(["Not reviewed", "In progress", "Reviewed"]), template: z.string().max(100), custom: z.record(z.string().min(1).max(60), text).refine(value => Object.keys(value).length <= 50) }),
  drawings: z.array(drawingSchema).max(500),
  evidence: z.array(z.object({ asset: imageAssetSchema.optional(), replayAt: z.number().finite().nonnegative().optional(), origin: z.enum(["upload", "clipboard"]).optional(), peerCapture: peerCapture.optional(), timeInterpretationVersion: z.string().max(160).optional(), id: z.string().min(1).max(200), name: z.string().max(240), image: z.union([z.literal(""), z.string().max(27_000_000).regex(/^data:image\/png;base64,[A-Za-z0-9+/]+=*$/)]), time: z.number().finite().nonnegative(), revision: z.number().int().nonnegative(), timeframe: z.string().max(40) }).refine(e => e.asset ? e.image === "" : e.image.startsWith("data:image/png;base64,"), "Supply an immutable asset reference or a legacy inline PNG, never both")).max(30),
  // Historical material is server-owned; never trust a client replacement.
  legacy: z.unknown().optional(),
});
