import { expect, test, type Page } from "@playwright/test";
import { defaultPreferences } from "../../src/lib/workstation/types";
import { DEMO_PREFIX } from "../../src/lib/workstation/demo";

const prefKey = "execution-lab:workstation:preferences:demo:v1";
async function open(page: Page) {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.addInitScript(({ prefs, key }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify({ ...prefs, averages: [5, 10, 20, 50], journal: true, panels: [{ id: "chart-1", interval: "1d", session: "regular" }] })); }, { prefs: defaultPreferences(), key: prefKey });
  await page.goto("/preview/trades?groupKey=demo-nvda");
  await expect(page.locator(".ws-chart").first()).toHaveAttribute("data-visible-from", /\d+/);
  if (await page.locator(".ws-mobile-tabs").isVisible()) await page.locator(".ws-mobile-tabs").getByRole("button", { name: "Journal", exact: true }).click();
  await page.locator("summary").filter({ hasText: /^Peers$/ }).click();
  await expect(page.getByRole("button", { name: "Compare peers", exact: true })).toBeEnabled();
  return errors;
}
const mainState = (page: Page) => page.evaluate(key => ({ preferences: localStorage.getItem(key), view: localStorage.getItem("execution-lab:workstation:demo:v1:view:demo-nvda"), ranges: [...document.querySelectorAll(".ws-chart")].map(e => [e.getAttribute("data-visible-from"), e.getAttribute("data-visible-to")]) }), prefKey);
const doc = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key) || "null"), DEMO_PREFIX + "demo-nvda");
test("50-peer virtualization, isolated linked navigation, paired capture, reuse, reload and detachment", async ({ page }) => {
  const errors = await open(page);
  await expect.poll(async () => (await mainState(page)).view).toBeTruthy();
  const before = await mainState(page);
  await page.getByRole("button", { name: "Compare peers", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Peer comparison", exact: true });
  await expect(dialog.locator('[data-peer-symbol="PEER01"] button', { hasText: "Attach comparison" })).toBeEnabled();
  await expect.poll(() => dialog.locator('[data-peer-symbol="PEER01"] canvas').evaluateAll(elements => {
    const colours = new Set<string>();
    for (const element of elements) {
      const canvas = element as HTMLCanvasElement;
      const pixels = canvas.getContext("2d")!.getImageData(0, 0, canvas.width, canvas.height).data;
      for (let i = 0; i < pixels.length; i += 4) if (pixels[i + 3] > 200) colours.add(`${pixels[i]},${pixels[i + 1]},${pixels[i + 2]}`);
    }
    return ["245,158,11", "96,165,250", "192,132,252", "244,114,182"].every(rgb => colours.has(rgb));
  })).toBe(true);
  expect(await dialog.locator("[data-peer-canvas]").count()).toBeLessThanOrEqual(11);
  await expect(dialog).toContainText("50 peers");
  await dialog.locator(".ws-peer-scroll").evaluate(e => { e.scrollTop = e.scrollHeight; });
  await expect(dialog.locator('[data-peer-symbol="PEER50"] [data-peer-canvas]')).toBeVisible();
  await expect(dialog.locator('[data-peer-symbol="PEER01"]')).toHaveCount(0);
  expect(await dialog.locator("[data-peer-canvas]").count()).toBeLessThanOrEqual(11);
  await dialog.getByLabel("Search peers").fill("PEER03");
  const peer = dialog.locator('[data-peer-symbol="PEER03"]');
  await expect(peer.getByRole("button", { name: "Attach comparison", exact: true })).toBeEnabled();
  await dialog.getByLabel("Peer timeframe").selectOption("1h");
  await expect(peer.getByRole("button", { name: "Attach comparison", exact: true })).toBeEnabled();
  await dialog.getByRole("button", { name: "Match workspace", exact: true }).click();
  await expect(dialog.getByLabel("Peer timeframe")).toHaveValue("1d");
  await expect(peer.getByRole("button", { name: "Attach comparison", exact: true })).toBeEnabled();
  const primary = dialog.locator(".ws-peer-primary [data-peer-canvas]");
  const peerCanvas = peer.locator("[data-peer-canvas]");
  await expect(peerCanvas).toHaveAttribute("data-visible-from", /\d+/);
  const box = (await peerCanvas.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.wheel(0, -160);
  await expect.poll(async () => (await primary.getAttribute("data-visible-from")) === (await peerCanvas.getAttribute("data-visible-from"))).toBe(true);
  await expect(peer.getByRole("button", { name: "Attach comparison", exact: true })).toBeEnabled();
  await dialog.getByRole("button", { name: "Link dates on", exact: true }).click();
  const primaryRange = await primary.getAttribute("data-visible-from");
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.wheel(0, -160);
  await expect.poll(() => primary.getAttribute("data-visible-from")).toBe(primaryRange);
  await expect(peer.getByRole("button", { name: "Attach comparison", exact: true })).toBeEnabled();
  await peer.getByRole("button", { name: "Attach comparison", exact: true }).click();
  await expect.poll(async () => (await doc(page))?.evidence?.length).toBe(1);
  const saved = await doc(page); expect(saved.evidence[0].peerCapture.symbols).toEqual(["NVDA", "PEER03"]);
  expect(saved.review.notion.sections.peers.evidenceIds).toEqual([saved.evidence[0].id]);
  await page.screenshot({ path: "artifacts/peer-comparison-desktop.png", fullPage: true });
  await dialog.getByRole("button", { name: "Close peer comparison" }).click();
  expect(await mainState(page)).toEqual(before);
  const takeaways = page.locator("details").filter({ has: page.locator("summary", { hasText: /^Takeaways$/ }) });
  await takeaways.locator("summary").click();
  await page.getByRole("button", { name: "Show Evidence", exact: true }).click();
  await page.locator(".ws-evidence-sections summary").click();
  await page.locator(".ws-evidence-sections").getByLabel("Takeaways", { exact: true }).check();
  await expect.poll(async () => (await doc(page))?.review.notion.sectionEvidence?.takeaways).toEqual([saved.evidence[0].id]);
  await page.reload();
  await page.locator("summary").filter({ hasText: /^Peers$/ }).click();
  await expect(page.locator(".ws-section-preview img")).toHaveCount(1);
  await page.locator("summary").filter({ hasText: /^Takeaways$/ }).click();
  await expect(takeaways.locator(".ws-section-preview img")).toHaveCount(1);
  await takeaways.getByRole("button", { name: /^Detach/ }).click();
  await expect.poll(async () => (await doc(page))?.review.notion.sectionEvidence?.takeaways).toEqual([]);
  expect((await doc(page)).evidence).toHaveLength(1); expect(errors).toEqual([]);
});
test("mobile uses a compact pinned primary and a single scrollable peer column", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await open(page);
  await page.getByRole("button", { name: "Compare peers", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Peer comparison", exact: true });
  await expect(dialog.locator('[data-peer-symbol="PEER01"] [data-peer-canvas]')).toBeVisible();
  const primary = (await dialog.locator(".ws-peer-primary").boundingBox())!, scroll = (await dialog.locator(".ws-peer-scroll").boundingBox())!;
  expect(primary.y + primary.height).toBeLessThanOrEqual(scroll.y); expect(primary.height).toBeLessThan(260);
  expect(await dialog.locator(".ws-peer-grid").evaluate(e => getComputedStyle(e).gridTemplateColumns.split(" ").length)).toBe(1);
  await page.screenshot({ path: "artifacts/peer-comparison-mobile.png", fullPage: true });
});
test("newest-first order drives initial selection, Save & next, search and mobile choices", async ({ page }) => {
  await open(page);
  await page.goto("/preview/trades");
  await expect(page.locator(".ws-trade-card.active")).toContainText("MSFT");
  expect(await page.locator(".ws-trade-card strong").allTextContents()).toEqual(["MSFT", "NVDA", "AAPL", "TSLA", "AMD", "META"]);
  await page.getByRole("button", { name: /Save & next/ }).click();
  await expect(page.locator(".ws-trade-card.active")).toContainText("NVDA");
  await page.getByLabel("Search trades", { exact: true }).fill("AAPL");
  await expect(page.locator(".ws-trade-card")).toHaveCount(1);
  await page.getByLabel("Search trades", { exact: true }).fill("");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.getByLabel("Choose trade", { exact: true }).locator("option").allTextContents()).toEqual(["MSFT · Sep 9, 2026", "NVDA · Sep 9, 2026", "AAPL · Sep 8, 2026", "TSLA · Sep 8, 2026", "AMD · Sep 7, 2026", "META · Sep 7, 2026"]);
});
