import { showTakeaways } from "./review-helpers";
import { expect, test, Page } from "@playwright/test";

async function open(page: Page) {
  const errors: string[] = [], requests: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/**", route => { requests.push(route.request().url()); return route.abort(); });
  await page.goto("/preview/trades?groupKey=demo-nvda");
  await expect(page.locator(".ws-chart-state")).toHaveCount(0);
  await expect(page.locator(".ws-chart").first()).toHaveAttribute("data-visible-from", /\d+/);
  return { errors, requests };
}
async function settings(page: Page) {
  await page.getByRole("button", { name: "Chart settings", exact: true }).click();
  await page.getByRole("button", { name: "Keyboard shortcuts", exact: false }).click();
  return page.getByRole("dialog", { name: "Keyboard shortcuts", exact: true });
}
test("chart shortcuts respect focus, typing and Escape priority; fullscreen and date navigation work", async ({ page }, info) => {
  const { errors, requests } = await open(page);
  const chart = page.locator(".ws-chart").nth(1);
  await chart.focus(); await page.keyboard.press("r");
  await expect(page.getByRole("button", { name: "Horizontal ray", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("Escape");
  await chart.focus(); await page.keyboard.press("f");
  await expect(chart).toHaveClass(/ws-chart-fullscreen/);
  await expect.poll(async () => (await chart.boundingBox())!.width).toBeGreaterThan(1800);
  await page.keyboard.press("n");
  await chart.locator(".ws-plot").click({ position: { x: 180, y: 130 } });
  const annotation = page.getByLabel("Annotation text", { exact: true });
  await expect(annotation).toBeVisible();
  await annotation.fill("Fullscreen chart annotation");
  await page.getByRole("button", { name: "Close annotation properties", exact: true }).click();
  await page.keyboard.press("g");
  const date = page.getByRole("dialog", { name: "Jump to date", exact: true });
  await expect(date).toBeVisible();
  const target = date.getByLabel("Jump target date UTC");
  await expect(target).toBeFocused();
  await target.fill("2026-09-09T15:00");
  await target.press("Enter");
  await expect(date).toBeHidden();
  await expect(chart).toHaveClass(/ws-chart-fullscreen/);
  await page.keyboard.press("r"); await page.keyboard.press("Escape");
  await expect(chart).toHaveClass(/ws-chart-fullscreen/);
  await page.screenshot({ path: info.outputPath("workstation-shortcut-fullscreen.png"), fullPage: true });
  await page.keyboard.press("Escape");
  await expect(chart).not.toHaveClass(/ws-chart-fullscreen/);
  await showTakeaways(page);
  const note = page.getByRole("textbox", { name: "Takeaways", exact: true });
  await note.fill("Typing keeps chart shortcuts inactive: "); await note.pressSequentially("rfgnh");
  await note.press("Control+Enter");
  await expect(note).toHaveText(/rfgnh/);
  await expect(page.locator(".ws-chart").first()).toHaveAttribute("aria-label", /NVDA/);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Select / pan", exact: true })).toHaveAttribute("aria-pressed", "true");
  await chart.focus(); await page.keyboard.press("Shift+F");
  await expect(page.locator(".workstation")).toHaveClass(/ws-focus/);
  await page.keyboard.press("Escape");
  await expect(page.locator(".workstation")).not.toHaveClass(/ws-focus/);
  expect(errors).toEqual([]); expect(requests).toEqual([]);
});
test("shortcut recording detects conflicts, updates tooltips, persists and can be disabled/reset", async ({ page }, info) => {
  const { errors, requests } = await open(page);
  const dialog = await settings(page);
  await dialog.getByLabel("Search keyboard shortcuts").fill("ray");
  const binding = dialog.getByRole("button", { name: "Set shortcut for Horizontal ray", exact: true });
  await binding.click(); await binding.press("h");
  await expect(dialog.getByRole("status")).toContainText("Already assigned to Horizontal line");
  await binding.press("Control+r");
  await expect(dialog.getByRole("status")).toContainText("reserved");
  await binding.press("Shift+Y");
  await expect(binding).toContainText("Shift + Y");
  await dialog.getByLabel("Search keyboard shortcuts").fill("");
  await page.screenshot({ path: info.outputPath("workstation-shortcut-settings-dark.png"), fullPage: true });
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(page.getByRole("button", { name: "Horizontal ray", exact: true })).toHaveAttribute("title", /Shift \+ Y/);
  await page.reload(); await showTakeaways(page);
  const chart = page.locator(".ws-chart").first(); await chart.focus(); await page.keyboard.press("r");
  await expect(page.getByRole("button", { name: "Horizontal ray", exact: true })).toHaveAttribute("aria-pressed", "false");
  await page.keyboard.press("Shift+Y");
  await expect(page.getByRole("button", { name: "Horizontal ray", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.keyboard.press("Escape"); await page.keyboard.press("?");
  await expect(dialog).toBeVisible();
  await dialog.getByLabel("Enable single-letter shortcuts", { exact: true }).uncheck();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await chart.focus(); await page.keyboard.press("Shift+Y");
  await expect(page.getByRole("button", { name: "Horizontal ray", exact: true })).toHaveAttribute("aria-pressed", "false");
  await settings(page); await dialog.getByRole("button", { name: "Reset all shortcuts", exact: true }).click();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.getByTitle("Appearance", { exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await settings(page);
  await page.screenshot({ path: info.outputPath("workstation-shortcut-settings-mobile-light.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(errors).toEqual([]); expect(requests).toEqual([]);
});
